In [1]:
pip install cvxpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import cvxpy as cp
import numpy as np
import matplotlib.pyplot as plt

We can formulate the optimal policy problem for and shipments between two blood banks as the following convex optimization problem:

$$
\begin{aligned}
&\text { minimize } \quad \kappa\|t\|_{1}+p^{\top}\left(B^{\top} \textbf{1}+\tilde{B}^{\top} \textbf{1}\right)\\
&\text { s.t. } \quad \quad B^{\top} \textbf{1} \leq s^{+}, \tilde{B}^{\top} \textbf{1} \leq \tilde{s}^{+}\\
& \quad \quad \quad \quad   s^{+}=s-t, \quad \tilde{s}^{+}=\tilde{s}+t\\
& \quad \quad \quad \quad s^{*} \geq 0 \quad \tilde{s}^{+} \geq 0\\
& \quad \quad \quad \quad B \textbf{1} \geq d \quad \tilde{B}_{1} \textbf{1} \geq \tilde{d}
\end{aligned}
$$

where

$d \in \mathbf{R}_{+}^{4}$, $\tilde{d} \in \mathbf{R}_{+}^{4}$, $s \in \mathbf{R}_{+}^{4}$, $ \tilde{s} \in \mathbf{R}_{+}^{4}$, $\tilde{B} \in \mathbf{R}_{+}^{4 \times 4}$, $B \in \mathbf{R}_{+}^{4 \times 4}$, $t \in \mathbf{R}^{4}$


b) Now, we solve the problem with the following data: 

$$
p=\left[\begin{array}{l}
4 \\
2 \\
2 \\
1
\end{array}\right], \quad d=\left[\begin{array}{c}
20 \\
5 \\
10 \\
15
\end{array}\right], \quad s=\left[\begin{array}{c}
30 \\
10 \\
5 \\
0
\end{array}\right], \quad \tilde{d}=\left[\begin{array}{c}
10 \\
25 \\
5 \\
15
\end{array}\right], \quad \tilde{s}=\left[\begin{array}{c}
5 \\
20 \\
15 \\
20
\end{array}\right]
$$

Setup

In [3]:
n = 4
B = cp.Variable((n,n))
B_tilde = cp.Variable((n,n))
t = cp.Variable(shape=(n))


k = .5
p = np.array([4, 2, 2, 1])
d = np.array([20, 5, 10, 15])
s = np.array([30, 10, 5, 0])
d_tilde = np.array([10, 25, 5, 15])
s_tilde = np.array([5, 20, 15, 20])
ones = np.ones(n)

Convex Optimization Problem

In [4]:
objective = cp.Minimize(k * cp.norm(t,1) + p.T @ (B.T @ ones + B_tilde.T @ ones))

constraints = [B.T @ ones <= s - t, 
               B_tilde.T @ ones <= s_tilde + t,
               s - t >= 0,
               s_tilde + t >= 0,
               B @ ones >= d,
               B_tilde @ ones >= d_tilde]
               
prob = cp.Problem(objective, constraints)
result = prob.solve()
print("The optimal cost is given by", result)
print("The optimal shipment vector t is given by", t.value)
print("The optimal policy B is given by", B.value)
print("The optimal policy B_tilde is given by", B_tilde.value)

The optimal cost is given by 262.4999999001123
The optimal shipment vector t is given by [-0.14619791 -1.22479343 -1.15184129 -2.47716738]
The optimal policy B is given by [[ 9.41154947e+00  4.68119836e+00  3.41296032e+00  2.49429184e+00]
 [ 5.66154947e+00  9.31198357e-01 -3.37039677e-01 -1.25570816e+00]
 [ 6.91154947e+00  2.18119836e+00  9.12960323e-01 -5.70815512e-03]
 [ 8.16154947e+00  3.43119836e+00  2.16296033e+00  1.24429185e+00]]
The optimal policy B_tilde is given by [[ 0.27595052  3.75630164  2.52453968  3.44320816]
 [ 4.02595052  7.50630164  6.27453968  7.19320816]
 [-0.97404948  2.50630164  1.27453968  2.19320816]
 [ 1.52595052  5.00630164  3.77453968  4.69320816]]


In the above we see the optimial shipment vector $\textbf{t}$ and the optimal policies $\textbf{B}$ and $\tilde{B}$ as well as the optimal cost.

Now, if we set $t=0$, i.e. shipments are not allowed, we can verify that the problem is then infeasible.

In [5]:
t = 0

In [6]:
objective = cp.Minimize(k * cp.norm(t,1) + p.T @ (B.T @ ones + B_tilde.T @ ones))

constraints = [B.T @ ones <= s - t, 
               B_tilde.T @ ones <= s_tilde + t,
               s - t >= 0,
               s_tilde + t >= 0,
               B @ ones >= d,
               B_tilde @ ones >= d_tilde]
               
prob = cp.Problem(objective, constraints)
prob.solve()

ValueError: ignored